### ISSUE TITLE
Could you clarify python and lib versions

### ISSUE THREAD

**Issue by kevinyuan** [zulfadlizainal/5G-NR-Data-Rates#1]
Dear zulfadlizainal,

I see the following errors with my current python3 enviroment and I think they might be caused by incorrect python/lib versions.

Could you  clarify python and lib versions for this repo ?

>python 5GNRTputSim.py
...
TypeError: maximum() takes from 2 to 3 positional arguments but 1 were given

>python 5GNRMaxDataRates.py
...
TypeError: read_excel() got an unexpected keyword argument 'encoding'

**Comment by zulfadlizainal** [comment]
I will try to run in my environment and get back to you once i got access to my development pc.

If by any chance you found the solution or how to make it better, I welcome any pull request from you.

**Comment by zulfadlizainal** [comment]
this [pr](https://github.com/zulfadlizainal/5G-NR-Data-Rates/pull/2) should be able to fix your issue.
you can install .yml file as your packages for your virtual environment.
